import esbuild from "esbuild";
import { builtinModules } from "node:module";
import { assertNoScriptCreation, stripScriptPolyfills } from "./scripts/esbuild-plugins.mjs";
import process from "process";

const builtins = [...builtinModules, ...builtinModules.map((m) => `node:${m}`)];

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	// ExcelJS ships a self-contained browser bundle (package.json "browser" field),
	// so the plugin does not depend on Node built-ins at runtime.
	platform: "browser",
	mainFields: ["browser", "module", "main"],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [stripScriptPolyfills],
});

if (prod) {
	await context.rebuild();
	await assertNoScriptCreation("main.js");
	process.exit(0);
} else {
	await context.watch();
}
